terafoundation:
  connectors:
    elasticsearch-next:
      es7:
        node:
          - "http://elasticsearch7-master:9200"
      os2:
        node:
          - "http://opensearch2:9200"
  environment: development
  log_level: debug
  workers: 1
terasliceJobSettingsController:
  connections:
    store:
      connector: es7
      index: percent-to-keep
      document_id: noaa-2025-01-sample-v1
    sample:
      connector: os2
      index: noaa-2025-01-sample-v1
  window_ms: 60000
  target_rate: 0.002219
  initial_percent_kept: 75
  pid_constants: [0.25, 0.01, 0.1]
